spring:
  application:
    name: api-gateway
server:
  port: 8888

# 路由配置
zuul:
  routes:
    api-docapp:  # 路由节点，自定义
      path: /docapp/**   # 路径
      serviceId: edapp-service  # 服务名字
    api-docserver:
      path: /docserver/**
      serviceId: doctor-service
    flow-design:
      path: /flow/**
      serviceId: flow-design
  ignored-patterns: /**/hello/**  # /hello不能直接路由
  ws:
    brokerages:
      flow-design:
        end-points: topicServer,queueServer
        brokers: /topic,/user,/queue
      #  destination-prefixes:
  host:
    connect-timeout-millis: 15000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000   #socket超时
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 60000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  #eureka注册中心地址

#ribbon:
#  eureka:
#    enabled: false

# 多实例配置
#edapp-service: # 对应的是serviceId对应的值
#  ribbon:
#    listOfServers:
#      - http://localhost:8080
#      - http://localhost:8081
