spring:
  application:
    name: api-gateway
server:
  port: 8888

# 路由配置
zuul:
  routes:
    api-docapp:  # 路由节点，自定义
      path: /docapp/**   # 路径
      serviceId: edapp-service  # 服务名字
    api-docserver:
      path: /docserver/**
      serviceId: doctor-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  #eureka注册中心地址

#ribbon:
#  eureka:
#    enabled: false

# 多实例配置
#edapp-service: # 对应的是serviceId对应的值
#  ribbon:
#    listOfServers:
#      - http://localhost:8080
#      - http://localhost:8081